#!/bin/bash

echo "Cache Deployment Script for Investor Edge"
echo "========================================"
echo ""
echo "This script will help you deploy the cache files to your Render instance."
echo ""
echo "Option 1: Manual Copy via SSH"
echo "-----------------------------"
echo "1. SSH into your Render instance:"
echo "   ssh deploy@ssh-oregon.render.com"
echo ""
echo "2. Create the cache directory:"
echo "   mkdir -p /opt/render/project/src/data/cache"
echo ""
echo "3. Exit SSH and copy files from your local machine:"
echo "   scp data/cache/*.json deploy@ssh-oregon.render.com:/opt/render/project/src/data/cache/"
echo ""
echo "Option 2: Using Render Shell"
echo "---------------------------"
echo "1. Go to your Render dashboard"
echo "2. Click on your service → 'Shell' tab"
echo "3. Run these commands:"
echo ""
echo "mkdir -p data/cache"
echo ""
echo "# Then create each file manually in the shell"
echo "# Copy the contents from data/cache/*.json files"
echo ""
echo "Option 3: Environment-based Cache"
echo "--------------------------------"
echo "Since the cache files are ready, you can also:"
echo "1. Create a startup script that copies embedded cache data"
echo "2. Use the pre-populated cache files that are included in this directory"
echo ""
echo "The cache files are located in: $(pwd)/data/cache/"
echo "Total cache files: $(ls -1 data/cache/*.json 2>/dev/null | wc -l)"